const crypto=require('crypto');const A=require('./_auth');
const H={"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Authorization,Content-Type","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Cache-Control":"no-store"};const out=(s,d)=>({statusCode:s,headers:H,body:JSON.stringify(d)});
async function rest(path,options={}){const r=await fetch(A.SUPABASE_URL+'/rest/v1/'+path,{...options,headers:A.serviceHeaders(options.headers||{})});const t=await r.text();if(!r.ok)throw new Error(t);return t?JSON.parse(t):null}
function clientIp(event){const h=event.headers||{},f=h['x-forwarded-for']||h['X-Forwarded-For']||'';return String(h['x-nf-client-connection-ip']||h['cf-connecting-ip']||f.split(',')[0]||'').trim()}
function hashIp(ip){const secret=process.env.REFERRAL_IP_HASH_SECRET||process.env.PROMO_IP_HASH_SECRET||process.env.SUPABASE_SERVICE_ROLE_KEY;if(!secret)throw new Error('referral_hash_secret_missing');return crypto.createHmac('sha256',secret).update(ip).digest('hex')}
exports.handler=async event=>{if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:H};const u=await A.user(event);if(!u?.id||!u?.email)return out(401,{error:'unauthorized'});try{
 let profiles=await rest('referral_profiles?user_id=eq.'+u.id+'&select=code');if(!profiles.length){const code=crypto.randomBytes(5).toString('base64url').toUpperCase();await rest('referral_profiles?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates'},body:JSON.stringify({user_id:u.id,code})});profiles=await rest('referral_profiles?user_id=eq.'+u.id+'&select=code')}
 if(event.httpMethod==='POST'){const b=JSON.parse(event.body||'{}'),code=String(b.code||'').trim().toUpperCase(),ip=clientIp(event);if(!/^[A-Z0-9_-]{3,40}$/.test(code)||!ip)return out(400,{error:'invalid_referral'});const rpc=await fetch(A.SUPABASE_URL+'/rest/v1/rpc/register_referral_and_reward',{method:'POST',headers:A.serviceHeaders(),body:JSON.stringify({p_code:code,p_referred_user_id:u.id,p_referred_email:u.email.toLowerCase(),p_ip_hash:hashIp(ip)})});const result=await rpc.json().catch(()=>null);if(!rpc.ok)throw new Error(JSON.stringify(result));if(!result?.ok)return out(400,{error:result?.reason||'invalid_referral'});}
 const refs=await rest('referrals?referrer_user_id=eq.'+u.id+'&select=status,reward_mode,referrer_days_awarded,referred_days_awarded,rewarded_at,created_at,paid_at&order=created_at.desc'),ledger=await rest('credit_ledger?user_id=eq.'+u.id+'&select=amount_cents,kind,description,available_at,reversed_at,created_at&order=created_at.desc'),configs=await rest('referral_reward_config?singleton=eq.true&select=mode,referrer_days,referred_days,campaign_ends_at');const now=Date.now(),balance=ledger.filter(x=>!x.reversed_at&&new Date(x.available_at).getTime()<=now).reduce((s,x)=>s+x.amount_cents,0);return out(200,{code:profiles[0].code,balance_cents:balance,referrals:refs,ledger,reward_config:configs[0]||{mode:'credit'}});
 }catch(e){console.error('referral failed',e.message);return out(500,{error:'referral_failed'})}};
