const crypto=require('crypto');const A=require('./_auth');
const H={"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Authorization,Content-Type","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Cache-Control":"no-store"};const out=(s,d)=>({statusCode:s,headers:H,body:JSON.stringify(d)});
async function rest(path,options={}){const r=await fetch(`${A.SUPABASE_URL}/rest/v1/${path}`,{...options,headers:A.serviceHeaders(options.headers||{})});const t=await r.text();if(!r.ok)throw new Error(t);return t?JSON.parse(t):null}
exports.handler=async event=>{if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:H};const u=await A.user(event);if(!u)return out(401,{error:'unauthorized'});try{
 let profiles=await rest(`referral_profiles?user_id=eq.${u.id}&select=code`);if(!profiles.length){const code=crypto.randomBytes(5).toString('base64url').toUpperCase();await rest('referral_profiles?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates'},body:JSON.stringify({user_id:u.id,code})});profiles=await rest(`referral_profiles?user_id=eq.${u.id}&select=code`)}
 if(event.httpMethod==='POST'){const b=JSON.parse(event.body||'{}'),code=String(b.code||'').trim().toUpperCase();if(!code)return out(400,{error:'invalid_code'});const owner=await rest(`referral_profiles?code=eq.${encodeURIComponent(code)}&select=user_id,code`);if(!owner.length||owner[0].user_id===u.id)return out(400,{error:'invalid_referral'});await rest('referrals?on_conflict=referred_user_id',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates'},body:JSON.stringify({referred_user_id:u.id,referrer_user_id:owner[0].user_id,code})});}
 const [refs,ledger]=await Promise.all([rest(`referrals?referrer_user_id=eq.${u.id}&select=status,created_at,paid_at&order=created_at.desc`),rest(`credit_ledger?user_id=eq.${u.id}&select=amount_cents,kind,description,available_at,reversed_at,created_at&order=created_at.desc`)]);const now=Date.now(),balance=ledger.filter(x=>!x.reversed_at&&new Date(x.available_at).getTime()<=now).reduce((s,x)=>s+x.amount_cents,0);return out(200,{code:profiles[0].code,balance_cents:balance,referrals:refs,ledger});
 }catch(e){return out(500,{error:'referral_failed'})}};

