# -*- coding: utf-8 -*-
"""Casa traduções (por ORDEM) com as fontes de _to_translate.json e grava
reports/deepseek-interface-translations.json no formato do aplicador.
Fase 1: id + ru (prioridade)."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
gaps = json.loads((ROOT/'reports/_to_translate.json').read_text(encoding='utf-8'))

ID = [
 "← Kembali ke Podcast","⚔️ Aksi","🌍 Simulasi lengkap ini juga tersedia dalam 9 bahasa lainnya",
 "🎧 Podcast dalam Bahasa Jerman","1.312 kata kerja","23 cerita dwibahasa","38.802 kalimat",
 "38.802 kalimat terkonjugasi","4.500 frasa profesional","7 hari","90 · 4.500 frasa",
 "Sebagai pelengkap perpustakaan lengkap, Anda dapat mengikuti rangkaian 30 pelajaran dengan dialog, audio, penjelasan, dan latihan. Ini jalur yang tertata bagi yang lebih suka belajar langkah demi langkah.",
 "Saat Anda berbicara, peramban mencoba menampilkan teks secara langsung. Saat berhenti, transkripsi akhir audio ditambahkan ke kotak teks.",
 "Menulis — DeutschBloom","Cerita dwibahasa untuk didengarkan dengan headphone: bahasa Jerman diikuti terjemahannya, kalimat demi kalimat.",
 "Tidak! Anda bisa menjelajahi dialog, kata kerja, bahasa gaul, kuis, dan banyak lagi tanpa perlu mendaftar. Premium membuka seluruh perpustakaan (lebih dari 59.000 item) kapan pun Anda ingin melangkah lebih jauh.",
 "Podcast — DeutschBloom","Fitur Kursus A1 Terpandu","Kosakata — DeutschBloom",
 ", tanpa ribet — batalkan kapan saja.","(R$ 100 lebih murah daripada kartu) — hanya untuk 100 pelanggan pertama.",
 "/bulan","← Kembali ke Kursus","← Kembali ke Musik",
 "+1.500 ungkapan sehari-hari bahasa Jerman asli — dari bahasa gaul jalanan hingga idiom.",
 "⚡ Kuis Cepat","🎙️ Rekaman tersimpan di perangkat ini","🎧 Rekaman Anda:","🎵 Musik","🐍 Berburu Kosakata",
 "💾 Simpan","📆 7 hari","🔊 Dengarkan asli","🗓️ 30 hari","🗣️ Ungkapan & Bahasa Gaul",
 "1.225 dialog + 1.315 kata kerja terkonjugasi","1.509 bahasa gaul dan 4.500 frasa profesi",
 "20 konten dari setiap kategori","25 kategori tematik","3.000 soal kuis + simulasi Goethe","30 hari",
 "59.000+ konten","Mulai dari R$ 14,99/bulan","Akses seumur hidup seharga R$ 297","Administrasi | DeutschBloom",
 "bahasa Jerman sehari-hari","Arahkan kamera aplikasi bank Anda ke kode QR — nilainya sudah terisi otomatis",
 "Belajar bahasa Jerman dengan lirik terterjemah, baris demi baris.","Belajar Bahasa Jerman dari A1 hingga C2 | DeutschBloom",
 "Audio berkualitas tinggi di semua konten","Lanjutan","Blokir / tangguhkan akun","Dasar",
 "Selamat datang di DeutschBloom. Belajar dengan cara Anda.","Berburu Kosakata — DeutschBloom","Buku Catatan — DeutschBloom",
 "Memuat kuis...","Memuat progres Anda...","Klik untuk mengungkap","Klik untuk melihat terjemahan","dengan lirik terterjemah",
 "Berikan paket","selesai","Bisakah saya belajar meski mulai dari nol?",
 "Akun dengan jumlah permintaan yang sangat tinggi dalam sehari mungkin menyalin konten alih-alih belajar. Periksa sebelum bertindak.",
 "contato@alemaofacilbrasil.com.br","DeutschBloom © 2026 — ruang tenang untuk benar-benar belajar.","Dialog — DeutschBloom",
 "hari berturut-turut","Langsung di halaman","dari A1 hingga C2 — dengan harga lebih murah daripada sekali jajan per bulan.",
 "Dari A1 dasar hingga C2 lanjutan, dengan jalur yang menemani Anda.",
 "Pertanyaan, saran, masalah teknis, atau ingin bicara soal kemitraan? Hubungi kami.","Akhiri dan simpan XP","Temukan dalam bahasa Jerman:",
 "Selagi Pix otomatis belum siap, Anda bisa membayar langsung dan kami membuka akses Anda dalam waktu hingga",
 "Dengan masuk, batas Anda terlindungi.","setara R$ 12,42/bulan · pembayaran tahunan sekali",
 "Pilih level Anda. Di setiap ronde Anda menemukan satu kalimat singkat, menjawab kuis, dan meninjau satu kata kerja dari koleksi kami.",
 "Pilih level untuk memulai.","Pilih level untuk melihat dialog dan kata kerja.","Menyimak dan pelafalan yang jelas",
 "Jelajahi konten gratis sebelum memilih paket.","Ungkapan — DeutschBloom","Berbicara, berpikir, dan menyusun dalam bahasa Jerman",
 "kalimat dengan audio","kalimat tersedia","Riwayat Pix (disetujui dan ditolak)","Sama seperti yang muncul saat Anda membayar",
 "Menengah","Buka perpustakaan lengkap, simulasi Goethe, audio berkualitas tinggi, dan sinkronisasi progres Anda.",
 "Lebih dari","Pesan untuk kami (opsional — waktu pembayaran, dll.)","Apakah progres saya tersimpan?",
 "Ribuan kalimat dengan audio penutur asli, selain yang keluar di ujian:","Susun perjalanan Anda","Musik — DeutschBloom",
 "Musik","Belum ada rekaman","Level (A1→C2)","Nama yang muncul di bukti Pix",
 "Audio hanya tersimpan di perangkat ini, tidak dikirim bersama analisis.","konten",
 "Premium membuka perpustakaan lengkap, simulasi Goethe, audio berkualitas tinggi, dan sinkronisasi progres antarperangkat.",
 "Apa yang termasuk dalam paket Premium?","Seumur Hidup seharga R$ 197 dengan Pix","Dengarkan","kata · minimum yang disarankan:",
 "selamanya · tanpa kartu","Paket untuk Belajar Bahasa Jerman | DeutschBloom","Mengapa belajar di DeutschBloom",
 "Berlatih dengan soal bergaya ujian resmi — berdasarkan konten kursus.","Menyiapkan misi hari ini...","Profesi — DeutschBloom",
 "Progres tersinkron di cloud","Pelafalan — DeutschBloom","Paket mana yang Anda bayar?","Kuis penempatan","Kuis Cepat — DeutschBloom",
 "R$ 14,99/bulan","Radio lo-fi dan Pomodoro","Mengalihkan ke",
 "Jawab situasi nyata, latih spontanitas Anda, dan temukan cara membuat bahasa Jerman Anda lebih jelas dan alami.",
 "Respons cepat pada jam kerja","Tanpa jatuh tempo","Sesi cepat","Sesi Cepat Bahasa Jerman | DeutschBloom","Langkah pertama Anda, tanpa tekanan",
 "Ya, untuk akun dengan login, progres tersinkron di cloud. Tanpa login, tersimpan hanya di peramban ini.",
 "Ya. Konten tertata dari A1 hingga C2, memungkinkan mulai dari dasar dan maju bertahap dengan dialog, kosakata, audio, dan latihan.",
 "Ya. Paket gratis memungkinkan mengenal lingkungan dan mempelajari sebagian konten tanpa memasukkan kartu.","Sistem XP dan level",
 "Hanya untuk 100 pelanggan pertama: bayar sekali, pakai selamanya — termasuk semua yang akan kami rilis.","Permintaan Pix tertunda",
 "Tes Kreativitas dalam Bahasa Jerman | DeutschBloom","Uji refleks bahasa Jerman Anda — cepat, seru, bikin ketagihan.",
 "Semua bahasa Jerman, tanpa mengganggu ritme Anda.","Semua","Semua 59.000 item terbuka","latih menulis","Akses terakhir",
 "Latihan singkat untuk maju","Pakai gratis","Gunakan tombol panah keyboard (atau tombol) untuk membawa ular ke kata Jerman yang benar.",
 "Penggunaan konten hari ini (kemungkinan unduhan massal)","Pengguna terdaftar","Seumur Hidup","Seumur Hidup (Pendiri) — R$ 197 dengan Pix",
 "Anda bisa mengubahnya kapan saja. Jika tidak memilih, kami memakai 15 menit dalam empat hari per minggu.",
 "Simulasi ini gratis. Kursus lengkap adalah Premium.",
]

RU = [
 "← Назад к подкастам","⚔️ Экшен","🌍 Этот полный пробный тест также доступен ещё на 9 языках",
 "🎧 Подкасты на немецком","1.312 глаголов","23 двуязычные истории","38.802 фразы",
 "38.802 спрягаемые фразы","4.500 профессиональных фраз","7 дней","90 · 4.500 фраз",
 "Как дополнение к полной библиотеке, вы можете пройти серию из 30 уроков с диалогом, аудио, объяснением и упражнениями. Это упорядоченный путь для тех, кто предпочитает учиться шаг за шагом.",
 "Пока вы говорите, браузер пытается показывать текст в реальном времени. Когда вы остановитесь, итоговая расшифровка аудио добавляется в текстовое поле.",
 "Письмо — DeutschBloom","Двуязычные истории для прослушивания в наушниках: немецкий, а затем перевод, фраза за фразой.",
 "Нет! Вы можете изучать диалоги, глаголы, сленг, викторины и многое другое без всякой регистрации. Premium открывает всю библиотеку (более 59.000 материалов), когда вы захотите пойти дальше.",
 "Подкасты — DeutschBloom","Возможности курса A1 с сопровождением","Словарь — DeutschBloom",
 ", без бюрократии — отмените в любой момент.","(на R$ 100 дешевле, чем картой) — только для первых 100 подписчиков.",
 "/мес","← Назад к курсам","← Назад к музыке",
 "+1.500 разговорных выражений настоящего немецкого — от уличного сленга до идиом.",
 "⚡ Быстрая викторина","🎙️ Записи, сохранённые на этом устройстве","🎧 Ваша запись:","🎵 Музыка","🐍 Охота за словами",
 "💾 Сохранить","📆 7 дней","🔊 Слушать оригинал","🗓️ 30 дней","🗣️ Выражения и сленг",
 "1.225 диалогов + 1.315 спряжённых глаголов","1.509 сленговых слов и 4.500 фраз по профессиям",
 "20 материалов из каждой категории","25 тематических категорий","3.000 вопросов викторины + пробные тесты Goethe","30 дней",
 "59.000+ материалов","От R$ 14,99/мес","Пожизненный доступ за R$ 297","Администрирование | DeutschBloom",
 "повседневный немецкий","Наведите камеру банковского приложения на QR-код — сумма уже подставлена",
 "Учите немецкий по переведённым текстам песен, строка за строкой.","Учите немецкий с A1 до C2 | DeutschBloom",
 "Высококачественное аудио во всём контенте","Продвинутый","Заблокировать / приостановить аккаунт","Базовый",
 "Добро пожаловать в DeutschBloom. Учитесь так, как вам удобно.","Охота за словами — DeutschBloom","Блокнот — DeutschBloom",
 "Загрузка викторин...","Загрузка вашего прогресса...","Нажмите, чтобы открыть","Нажмите, чтобы увидеть перевод","с переведёнными текстами",
 "Предоставить план","завершено","Смогу ли я учиться, даже начиная с нуля?",
 "Аккаунты с очень большим числом запросов за день могут копировать контент вместо учёбы. Проверьте, прежде чем действовать.",
 "contato@alemaofacilbrasil.com.br","DeutschBloom © 2026 — спокойное место, чтобы учиться по-настоящему.","Диалог — DeutschBloom",
 "дней подряд","Прямо на странице","с A1 до C2 — дешевле, чем один перекус в месяц.",
 "От базового A1 до продвинутого C2, с маршрутом, который идёт рядом с вами.",
 "Вопрос, предложение, техническая проблема или хотите обсудить партнёрство? Напишите нам.","Завершить и сохранить XP","Найдите на немецком:",
 "Пока автоматический Pix не готов, вы можете заплатить напрямую, и мы откроем вам доступ в течение",
 "Войдя, вы защищаете свой лимит.","равно R$ 12,42/мес · единый годовой платёж",
 "Выберите свой уровень. В каждом раунде вам встречается короткая фраза, вы отвечаете на викторину и повторяете глагол из нашей коллекции.",
 "Выберите уровень, чтобы начать.","Выберите уровень, чтобы увидеть диалоги и глаголы.","Чёткое восприятие на слух и произношение",
 "Изучайте бесплатный контент, прежде чем выбрать план.","Выражения — DeutschBloom","Говорите, думайте и стройте фразы на немецком",
 "фраз с аудио","доступно фраз","История Pix (одобренные и отклонённые)","Так же, как отобразилось у вас при оплате",
 "Средний","Откройте полную библиотеку, пробные тесты Goethe, высококачественное аудио и синхронизацию вашего прогресса.",
 "Более","Сообщение нам (необязательно — время оплаты и т. п.)","Мой прогресс сохраняется?",
 "Тысячи фраз с аудио носителей, помимо того, что бывает на экзамене:","Составьте свой маршрут","Музыка — DeutschBloom",
 "Музыка","Пока нет записей","Уровень (A1→C2)","Имя, которое отображается в квитанции Pix",
 "Аудио остаётся только на этом устройстве, оно не отправляется вместе с анализом.","контент",
 "Premium открывает полную библиотеку, пробные тесты Goethe, высококачественное аудио и синхронизацию прогресса между устройствами.",
 "Что входит в план Premium?","Пожизненный за R$ 197 при оплате Pix","Слушать","слов · рекомендуемый минимум:",
 "навсегда · без карты","Планы для изучения немецкого | DeutschBloom","Почему стоит учиться в DeutschBloom",
 "Тренируйтесь на вопросах в стиле официального экзамена — на основе контента курсов.","Готовим вашу сегодняшнюю миссию...","Профессии — DeutschBloom",
 "Прогресс синхронизирован в облаке","Произношение — DeutschBloom","Какой план вы оплатили?","Тест на определение уровня","Быстрая викторина — DeutschBloom",
 "R$ 14,99/мес","Радио lo-fi и Pomodoro","Перенаправление на",
 "Отвечайте на реальные ситуации, тренируйте спонтанность и узнайте, как сделать ваш немецкий яснее и естественнее.",
 "Быстрый ответ в рабочее время","Без срока действия","Быстрая сессия","Быстрая сессия немецкого | DeutschBloom","Ваш первый путь, без давления",
 "Да, для аккаунтов со входом прогресс синхронизируется в облаке. Без входа он сохраняется только в этом браузере.",
 "Да. Контент организован от A1 до C2, что позволяет начать с базового и постепенно продвигаться с диалогами, словарём, аудио и упражнениями.",
 "Да. Бесплатный план позволяет познакомиться со средой и изучать часть контента без ввода карты.","Система XP и уровней",
 "Только для первых 100 подписчиков: заплатите один раз, пользуйтесь всегда — включая всё, что мы ещё выпустим.","Ожидающие запросы Pix",
 "Тест на креативность на немецком | DeutschBloom","Проверьте свою реакцию на немецком — быстро, весело, затягивает.",
 "Весь немецкий, не прерывая ваш ритм.","Все","Все 59.000 материалов открыты","тренируйте письмо","Последний вход",
 "Короткая практика, чтобы продвинуться","Пользоваться бесплатно","Стрелками клавиатуры (или кнопками) ведите змейку к нужному немецкому слову.",
 "Использование контента сегодня (возможна массовая загрузка)","Зарегистрированные пользователи","Пожизненный","Пожизненный (Основатель) — R$ 197 через Pix",
 "Вы можете изменить это в любой момент. Если не выберете, мы используем 15 минут в четыре дня в неделю.",
 "За две минуты узнайте свой уровень — от A1 до C2 — и с чего начать.",
 "бесплатные двуязычные истории","Бесплатный онлайн-тест по немецкому","Бесплатный онлайн-тест по немецкому — уровень за 2 минуты | DeutschBloom",
]

out = {}
for loc, arr in (('id', ID), ('ru', RU)):
    src = gaps[loc]
    assert len(arr) == len(src), f"{loc}: traduções {len(arr)} != fontes {len(src)}"
    out[loc] = dict(zip(src, arr))

payload = {"translations": out}
(ROOT/'reports/deepseek-interface-translations.json').write_text(json.dumps(payload, ensure_ascii=False, indent=1), encoding='utf-8')
print("id:", len(out['id']), "ru:", len(out['ru']), "-> deepseek-interface-translations.json")
