# -*- coding: utf-8 -*-
"""Adiciona os ~26 rótulos novos aos 9 idiomas antigos (en..pl), casando por
ORDEM com gaps de _to_translate.json. Merge em translations.json."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
gaps = json.loads((ROOT/'reports/_to_translate.json').read_text(encoding='utf-8'))
f = ROOT/'reports/deepseek-interface-translations.json'
payload = json.loads(f.read_text(encoding='utf-8'))
T = payload['translations']

TR = {
"en":["← Back to Podcasts","▶ Start the course","⚔️ Action","🌍 This full mock exam is also available in 9 more languages","🎓 Guided A1 Course","🎙️ Recordings","🎧 Podcasts","🎧 German Podcasts","📰 Blog","1.312 verbs","23 bilingual stories","38.802 sentences","38.802 conjugated sentences","4.500 professional phrases","7 days","90 · 4.500 phrases","As a complement to the full library, you can follow a sequence of 30 lessons with dialogue, audio, explanation, and exercises. It's an organized path for those who prefer to study step by step.","As you speak, the browser tries to show the text live. When you stop, the final transcription of the audio is added to the text box.","Writing — DeutschBloom","Bilingual stories to listen to with headphones: German followed by the translation, sentence by sentence.","No! You can explore dialogues, verbs, slang, quizzes, and much more without any sign-up. Premium unlocks the entire library (over 59.000 items) whenever you want to go further.","Podcasts — DeutschBloom","Guided A1 Course features","Vocabulary — DeutschBloom","Month","Week"],
"es":["← Volver a Podcasts","▶ Empezar el curso","⚔️ Acción","🌍 Este simulacro completo también está disponible en 9 idiomas más","🎓 Curso Guiado A1","🎙️ Grabaciones","🎧 Podcasts","🎧 Podcasts en alemán","📰 Blog","1.312 verbos","23 historias bilingües","38.802 frases","38.802 frases conjugadas","4.500 frases profesionales","7 días","90 · 4.500 frases","Como complemento de la biblioteca completa, puedes seguir una secuencia de 30 lecciones con diálogo, audio, explicación y ejercicios. Es un camino organizado para quienes prefieren estudiar paso a paso.","Mientras hablas, el navegador intenta mostrar el texto en vivo. Al detenerte, la transcripción final del audio se añade al cuadro de texto.","Escritura — DeutschBloom","Historias bilingües para escuchar con auriculares: alemán seguido de la traducción, frase por frase.","¡No! Puedes explorar diálogos, verbos, jerga, cuestionarios y mucho más sin ningún registro. Premium desbloquea toda la biblioteca (más de 59.000 elementos) cuando quieras ir más allá.","Podcasts — DeutschBloom","Funciones del Curso Guiado A1","Vocabulario — DeutschBloom","Mes","Semana"],
"fr":["← Retour aux Podcasts","▶ Commencer le cours","⚔️ Action","🌍 Cet examen blanc complet est aussi disponible en 9 autres langues","🎓 Cours guidé A1","🎙️ Enregistrements","🎧 Podcasts","🎧 Podcasts en allemand","📰 Blog","1.312 verbes","23 histoires bilingues","38.802 phrases","38.802 phrases conjuguées","4.500 phrases professionnelles","7 jours","90 · 4.500 phrases","En complément de la bibliothèque complète, vous pouvez suivre une série de 30 leçons avec dialogue, audio, explication et exercices. C'est un parcours organisé pour ceux qui préfèrent étudier pas à pas.","Pendant que vous parlez, le navigateur essaie d'afficher le texte en direct. Lorsque vous vous arrêtez, la transcription finale de l'audio est ajoutée à la zone de texte.","Écriture — DeutschBloom","Histoires bilingues à écouter au casque : l'allemand suivi de la traduction, phrase par phrase.","Non ! Vous pouvez explorer dialogues, verbes, argot, quiz et bien plus sans aucune inscription. Premium débloque toute la bibliothèque (plus de 59.000 éléments) quand vous voulez aller plus loin.","Podcasts — DeutschBloom","Fonctionnalités du cours guidé A1","Vocabulaire — DeutschBloom","Mois","Semaine"],
"it":["← Torna ai Podcast","▶ Inizia il corso","⚔️ Azione","🌍 Questa simulazione completa è disponibile anche in altre 9 lingue","🎓 Corso guidato A1","🎙️ Registrazioni","🎧 Podcast","🎧 Podcast in tedesco","📰 Blog","1.312 verbi","23 storie bilingui","38.802 frasi","38.802 frasi coniugate","4.500 frasi professionali","7 giorni","90 · 4.500 frasi","Come complemento alla biblioteca completa, puoi seguire una sequenza di 30 lezioni con dialogo, audio, spiegazione ed esercizi. È un percorso organizzato per chi preferisce studiare passo dopo passo.","Mentre parli, il browser prova a mostrare il testo in tempo reale. Quando ti fermi, la trascrizione finale dell'audio viene aggiunta alla casella di testo.","Scrittura — DeutschBloom","Storie bilingui da ascoltare con le cuffie: il tedesco seguito dalla traduzione, frase per frase.","No! Puoi esplorare dialoghi, verbi, slang, quiz e molto altro senza alcuna registrazione. Premium sblocca l'intera biblioteca (oltre 59.000 elementi) quando vuoi andare oltre.","Podcast — DeutschBloom","Funzioni del corso guidato A1","Vocabolario — DeutschBloom","Mese","Settimana"],
"tr":["← Podcast'lere dön","▶ Kursa başla","⚔️ Aksiyon","🌍 Bu tam deneme sınavı 9 dilde daha mevcut","🎓 Rehberli A1 Kursu","🎙️ Kayıtlar","🎧 Podcastler","🎧 Almanca Podcastler","📰 Blog","1.312 fiil","23 iki dilli hikâye","38.802 cümle","38.802 çekimli cümle","4.500 mesleki ifade","7 gün","90 · 4.500 ifade","Tam kütüphaneyi tamamlayıcı olarak, diyalog, ses, açıklama ve alıştırmalar içeren 30 derslik bir dizi izleyebilirsiniz. Adım adım çalışmayı tercih edenler için düzenli bir yoldur.","Siz konuşurken tarayıcı metni canlı göstermeye çalışır. Durduğunuzda, sesin son dökümü metin kutusuna eklenir.","Yazma — DeutschBloom","Kulaklıkla dinlemek için iki dilli hikâyeler: Almancanın ardından cümle cümle çeviri.","Hayır! Diyalogları, fiilleri, argoyu, testleri ve çok daha fazlasını hiç kayıt olmadan keşfedebilirsiniz. Premium, daha ileri gitmek istediğinizde tüm kütüphaneyi (59.000'den fazla öğe) açar.","Podcastler — DeutschBloom","Rehberli A1 Kursu özellikleri","Kelime Bilgisi — DeutschBloom","Ay","Hafta"],
"ar":["← العودة إلى البودكاست","▶ ابدأ الدورة","⚔️ أكشن","🌍 هذا الاختبار التجريبي الكامل متوفر أيضًا بـ 9 لغات أخرى","🎓 دورة A1 الموجَّهة","🎙️ التسجيلات","🎧 بودكاست","🎧 بودكاست بالألمانية","📰 المدونة","1.312 فعلاً","23 قصة ثنائية اللغة","38.802 جملة","38.802 جملة مصرّفة","4.500 عبارة مهنية","7 أيام","90 · 4.500 عبارة","كمكمّل للمكتبة الكاملة، يمكنك متابعة سلسلة من 30 درسًا مع الحوار والصوت والشرح والتمارين. إنه مسار منظَّم لمن يفضّل الدراسة خطوة بخطوة.","أثناء تحدثك، يحاول المتصفح عرض النص مباشرة. وعند التوقف، تُضاف النسخة النهائية من الصوت إلى مربع النص.","الكتابة — DeutschBloom","قصص ثنائية اللغة للاستماع بالسماعات: الألمانية تليها الترجمة، جملة بجملة.","لا! يمكنك استكشاف الحوارات والأفعال والعامية والاختبارات وأكثر من ذلك بكثير دون أي تسجيل. يفتح Premium المكتبة بأكملها (أكثر من 59.000 عنصر) عندما تريد المضي أبعد.","بودكاست — DeutschBloom","مزايا دورة A1 الموجَّهة","المفردات — DeutschBloom","شهر","أسبوع"],
"he":["← חזרה לפודקאסטים","▶ להתחיל את הקורס","⚔️ אקשן","🌍 מבחן הדמיה מלא זה זמין גם ב-9 שפות נוספות","🎓 קורס A1 מודרך","🎙️ הקלטות","🎧 פודקאסטים","🎧 פודקאסטים בגרמנית","📰 בלוג","1.312 פעלים","23 סיפורים דו-לשוניים","38.802 משפטים","38.802 משפטים מוטים","4.500 ביטויים מקצועיים","7 ימים","90 · 4.500 ביטויים","כהשלמה לספרייה המלאה, אפשר לעקוב אחר רצף של 30 שיעורים עם דיאלוג, אודיו, הסבר ותרגילים. זהו מסלול מסודר למי שמעדיף ללמוד צעד אחר צעד.","בזמן שאתם מדברים, הדפדפן מנסה להציג את הטקסט בשידור חי. כשעוצרים, התמלול הסופי של האודיו מתווסף לתיבת הטקסט.","כתיבה — DeutschBloom","סיפורים דו-לשוניים להאזנה עם אוזניות: גרמנית ואחריה התרגום, משפט אחר משפט.","לא! אפשר לחקור דיאלוגים, פעלים, סלנג, חידונים ועוד הרבה בלי שום הרשמה. Premium פותח את כל הספרייה (יותר מ-59.000 פריטים) מתי שתרצו להעמיק.","פודקאסטים — DeutschBloom","תכונות של קורס A1 מודרך","אוצר מילים — DeutschBloom","חודש","שבוע"],
"hi":["← पॉडकास्ट पर वापस","▶ कोर्स शुरू करें","⚔️ एक्शन","🌍 यह पूरा मॉक टेस्ट 9 और भाषाओं में भी उपलब्ध है","🎓 निर्देशित A1 कोर्स","🎙️ रिकॉर्डिंग","🎧 पॉडकास्ट","🎧 जर्मन पॉडकास्ट","📰 ब्लॉग","1.312 क्रियाएँ","23 द्विभाषी कहानियाँ","38.802 वाक्य","38.802 संयुग्मित वाक्य","4.500 पेशेवर वाक्यांश","7 दिन","90 · 4.500 वाक्यांश","पूरी लाइब्रेरी के पूरक के रूप में, आप संवाद, ऑडियो, व्याख्या और अभ्यास के साथ 30 पाठों का क्रम अपना सकते हैं। यह उन लोगों के लिए एक व्यवस्थित रास्ता है जो कदम-दर-कदम पढ़ना पसंद करते हैं।","जब आप बोलते हैं, ब्राउज़र टेक्स्ट को लाइव दिखाने की कोशिश करता है। रुकने पर, ऑडियो का अंतिम ट्रांसक्रिप्शन टेक्स्ट बॉक्स में जोड़ दिया जाता है।","लेखन — DeutschBloom","हेडफ़ोन के साथ सुनने के लिए द्विभाषी कहानियाँ: पहले जर्मन, फिर अनुवाद, वाक्य दर वाक्य।","नहीं! आप बिना किसी पंजीकरण के संवाद, क्रियाएँ, स्लैंग, क्विज़ और बहुत कुछ देख सकते हैं। Premium पूरी लाइब्रेरी (59.000+ आइटम) खोल देता है जब आप आगे बढ़ना चाहें।","पॉडकास्ट — DeutschBloom","निर्देशित A1 कोर्स की विशेषताएँ","शब्दावली — DeutschBloom","महीना","सप्ताह","ट्रैक करें"],
"pl":["← Powrót do podcastów","▶ Rozpocznij kurs","⚔️ Akcja","🌍 Ten pełny egzamin próbny jest dostępny także w 9 innych językach","🎓 Kurs A1 z przewodnikiem","🎙️ Nagrania","🎧 Podcasty","🎧 Podcasty po niemiecku","📰 Blog","1.312 czasowników","23 dwujęzyczne historie","38.802 zdania","38.802 odmienione zdania","4.500 zwrotów zawodowych","7 dni","90 · 4.500 zwrotów","Jako uzupełnienie pełnej biblioteki możesz przejść sekwencję 30 lekcji z dialogiem, audio, wyjaśnieniem i ćwiczeniami. To uporządkowana ścieżka dla tych, którzy wolą uczyć się krok po kroku.","Gdy mówisz, przeglądarka próbuje pokazać tekst na żywo. Po zatrzymaniu końcowa transkrypcja audio jest dodawana do pola tekstowego.","Pisanie — DeutschBloom","Dwujęzyczne historie do słuchania w słuchawkach: niemiecki, a po nim tłumaczenie, zdanie po zdaniu.","Nie! Możesz przeglądać dialogi, czasowniki, slang, quizy i wiele więcej bez żadnej rejestracji. Premium odblokowuje całą bibliotekę (ponad 59.000 elementów), gdy zechcesz pójść dalej.","Podcasty — DeutschBloom","Funkcje kursu A1 z przewodnikiem","Słownictwo — DeutschBloom","Miesiąc","Tydzień"],
}

for loc, arr in TR.items():
    src = gaps[loc]
    assert len(arr) == len(src), f"{loc}: {len(arr)} != {len(src)}"
    T.setdefault(loc, {}).update(dict(zip(src, arr)))

f.write_text(json.dumps(payload, ensure_ascii=False, indent=1), encoding='utf-8')
print("locales agora:", {k: len(v) for k, v in T.items()})
